# coding: utf-8

"""
    Brawl Stars API

    Unofficial Swagger definition for the official Brawl Stars API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://github.com/heyudude/brawlstars-swagger
"""


from __future__ import absolute_import

import unittest
import datetime

import pybrawl
from pybrawl.models.battle_brawlers import BattleBrawlers  # noqa: E501
from pybrawl.rest import ApiException

class TestBattleBrawlers(unittest.TestCase):
    """BattleBrawlers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BattleBrawlers
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pybrawl.models.battle_brawlers.BattleBrawlers()  # noqa: E501
        if include_optional :
            return BattleBrawlers(
                id = 56, 
                name = '0', 
                power = 56, 
                trophies = 56
            )
        else :
            return BattleBrawlers(
        )

    def testBattleBrawlers(self):
        """Test BattleBrawlers"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
