# coding: utf-8

"""
    Brawl Stars API

    Unofficial Swagger definition for the official Brawl Stars API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pybrawl
from pybrawl.api.locations_api import LocationsApi  # noqa: E501
from pybrawl.rest import ApiException


class TestLocationsApi(unittest.TestCase):
    """LocationsApi unit test stubs"""

    def setUp(self):
        self.api = pybrawl.api.locations_api.LocationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_club_ranking(self):
        """Test case for get_club_ranking

        Get club rankings for a specific location  # noqa: E501
        """
        pass

    def test_get_location(self):
        """Test case for get_location

        Get location information  # noqa: E501
        """
        pass

    def test_get_locations(self):
        """Test case for get_locations

        List locations  # noqa: E501
        """
        pass

    def test_get_player_ranking(self):
        """Test case for get_player_ranking

        Get player rankings for a specific location  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
