# coding: utf-8

"""
    Brawl Stars API

    Unofficial Swagger definition for the official Brawl Stars API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://github.com/heyudude/brawlstars-swagger
"""


from __future__ import absolute_import

import unittest

import pybrawl
from pybrawl.api.players_api import PlayersApi  # noqa: E501
from pybrawl import Configuration
from pybrawl.rest import ApiException


class TestPlayersApi(unittest.TestCase):
    """PlayersApi unit test stubs"""

    def setUp(self):
        self.config = Configuration()
        self.config.access_token = self.config.api_key
        #self.api = pybrawl.api.players_api.PlayersApi()  # noqa: E501
        self.players = pybrawl.PlayersApi(pybrawl.ApiClient(self.config))

    def tearDown(self):
        pass

    def test_get_player(self):
        """Test case for get_player

        Get player information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
