# coding: utf-8

"""
    Brawl_Stars_API

    Unofficial Swagger definition for the official Brawl Stars API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://github.com/heyudude/brawlstars-swagger
"""


from __future__ import absolute_import

import unittest
import datetime

import pybrawl
from pybrawl.models.search_paging_cursors import SearchPagingCursors  # noqa: E501
from pybrawl.rest import ApiException

class TestSearchPagingCursors(unittest.TestCase):
    """SearchPagingCursors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SearchPagingCursors
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pybrawl.models.search_paging_cursors.SearchPagingCursors()  # noqa: E501
        if include_optional :
            return SearchPagingCursors(
                after = '0', 
                before = '0'
            )
        else :
            return SearchPagingCursors(
        )

    def testSearchPagingCursors(self):
        """Test SearchPagingCursors"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
