# coding: utf-8

"""
    Brawl Stars API

    Unofficial Swagger definition for the official Brawl Stars API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pybrawl
from pybrawl.models.club import Club  # noqa: E501
from pybrawl.rest import ApiException

class TestClub(unittest.TestCase):
    """Club unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Club
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pybrawl.models.club.Club()  # noqa: E501
        if include_optional :
            return Club(
                tag = '0', 
                name = '0', 
                badge_id = 56, 
                type = '0', 
                club_score = 56, 
                required_trophies = 56, 
                donations_per_week = 56, 
                club_war_trophies = 56, 
                club_chest_level = 56, 
                club_chest_max_level = 56, 
                members = 56, 
                location = None, 
                description = '0', 
                club_chest_status = '0', 
                club_chest_points = 56, 
                member_list = [
                    pybrawl.models.club_member.ClubMember(
                        tag = '0', 
                        name = '0', 
                        exp_level = 56, 
                        trophies = 56, 
                        role = '0', 
                        last_seen = '0', 
                        club_rank = 56, 
                        previousclub_rank = 56, 
                        donations = 56, 
                        donations_received = 56, 
                        club_chest_points = 56, )
                    ]
            )
        else :
            return Club(
        )

    def testClub(self):
        """Test Club"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
