# coding: utf-8

"""
    Brawl Stars API

    Unofficial Swagger definition for the official Brawl Stars API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pybrawl
from pybrawl.models.game_mode import GameMode  # noqa: E501
from pybrawl.rest import ApiException

class TestGameMode(unittest.TestCase):
    """GameMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GameMode
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pybrawl.models.game_mode.GameMode()  # noqa: E501
        if include_optional :
            return GameMode(
                id = 56, 
                name = '0'
            )
        else :
            return GameMode(
        )

    def testGameMode(self):
        """Test GameMode"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
