# coding: utf-8

"""
    Brawl Stars API

    Unofficial Swagger definition for the official Brawl Stars API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pybrawl
from pybrawl.models.club_ranking_list import ClubRankingList  # noqa: E501
from pybrawl.rest import ApiException

class TestClubRankingList(unittest.TestCase):
    """ClubRankingList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ClubRankingList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pybrawl.models.club_ranking_list.ClubRankingList()  # noqa: E501
        if include_optional :
            return ClubRankingList(
                items = [
                    pybrawl.models.club_ranked.ClubRanked(
                        tag = '0', 
                        name = '0', 
                        rank = 56, 
                        previous_rank = 56, 
                        location = pybrawl.models.location.Location(
                            id = 56, 
                            name = '0', 
                            is_country = True, 
                            country_code = '0', ), 
                        club_score = 56, 
                        badge_id = 56, 
                        members = 56, )
                    ], 
                paging = pybrawl.models.search_paging.SearchPaging(
                    cursors = pybrawl.models.search_paging_cursors.SearchPaging_cursors(
                        after = '0', 
                        before = '0', ), )
            )
        else :
            return ClubRankingList(
        )

    def testClubRankingList(self):
        """Test ClubRankingList"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
