# coding: utf-8

"""
    Brawl Stars API

    Unofficial Swagger definition for the official Brawl Stars API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pybrawl
from pybrawl.models.player_achievement import PlayerAchievement  # noqa: E501
from pybrawl.rest import ApiException

class TestPlayerAchievement(unittest.TestCase):
    """PlayerAchievement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PlayerAchievement
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pybrawl.models.player_achievement.PlayerAchievement()  # noqa: E501
        if include_optional :
            return PlayerAchievement(
                name = '0', 
                stars = 56, 
                value = 56, 
                target = 56, 
                info = '0'
            )
        else :
            return PlayerAchievement(
        )

    def testPlayerAchievement(self):
        """Test PlayerAchievement"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
