# coding: utf-8

"""
    Brawl Stars API

    Unofficial Swagger definition for the official Brawl Stars API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pybrawl
from pybrawl.models.player_ranking_list import PlayerRankingList  # noqa: E501
from pybrawl.rest import ApiException

class TestPlayerRankingList(unittest.TestCase):
    """PlayerRankingList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PlayerRankingList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pybrawl.models.player_ranking_list.PlayerRankingList()  # noqa: E501
        if include_optional :
            return PlayerRankingList(
                items = [
                    pybrawl.models.player_ranked.PlayerRanked(
                        tag = '0', 
                        name = '0', 
                        exp_level = 56, 
                        trophies = 56, 
                        rank = 56, 
                        previous_rank = 56, 
                        club = pybrawl.models.club_base.ClubBase(
                            tag = '0', 
                            name = '0', 
                            badge_id = 56, ), )
                    ], 
                paging = pybrawl.models.search_paging.SearchPaging(
                    cursors = pybrawl.models.search_paging_cursors.SearchPaging_cursors(
                        after = '0', 
                        before = '0', ), )
            )
        else :
            return PlayerRankingList(
        )

    def testPlayerRankingList(self):
        """Test PlayerRankingList"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
