# coding: utf-8

"""
    Brawl Stars API

    Unofficial Swagger definition for the official Brawl Stars API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pybrawl
from pybrawl.models.location_list import LocationList  # noqa: E501
from pybrawl.rest import ApiException

class TestLocationList(unittest.TestCase):
    """LocationList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LocationList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pybrawl.models.location_list.LocationList()  # noqa: E501
        if include_optional :
            return LocationList(
                items = [
                    pybrawl.models.location.Location(
                        id = 56, 
                        name = '0', 
                        is_country = True, 
                        country_code = '0', )
                    ], 
                paging = pybrawl.models.search_paging.SearchPaging(
                    cursors = pybrawl.models.search_paging_cursors.SearchPaging_cursors(
                        after = '0', 
                        before = '0', ), )
            )
        else :
            return LocationList(
        )

    def testLocationList(self):
        """Test LocationList"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
