# coding: utf-8

"""
    Brawl Stars API

    Unofficial Swagger definition for the official Brawl Stars API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://github.com/heyudude/brawlstars-swagger
"""


from __future__ import absolute_import

import unittest

import pybrawl
from pybrawl.api.battlelog_api import BattlelogApi  # noqa: E501
from pybrawl.rest import ApiException


class TestBattlelogApi(unittest.TestCase):
    """BattlelogApi unit test stubs"""

    def setUp(self):
        self.api = pybrawl.api.battlelog_api.BattlelogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_battlelog(self):
        """Test case for get_battlelog

        Get player's battlelog  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
