# coding: utf-8

"""
    Brawl Stars API

    Unofficial Swagger definition for the official Brawl Stars API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pybrawl
from pybrawl.models.season_statistics import SeasonStatistics  # noqa: E501
from pybrawl.rest import ApiException

class TestSeasonStatistics(unittest.TestCase):
    """SeasonStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SeasonStatistics
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pybrawl.models.season_statistics.SeasonStatistics()  # noqa: E501
        if include_optional :
            return SeasonStatistics(
                id = '0', 
                trophies = 56, 
                best_trophies = 56
            )
        else :
            return SeasonStatistics(
        )

    def testSeasonStatistics(self):
        """Test SeasonStatistics"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
