# coding: utf-8

"""
    Brawl Stars API

    Unofficial Swagger definition for the official Brawl Stars API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pybrawl
from pybrawl.models.player_detail import PlayerDetail  # noqa: E501
from pybrawl.rest import ApiException

class TestPlayerDetail(unittest.TestCase):
    """PlayerDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PlayerDetail
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pybrawl.models.player_detail.PlayerDetail()  # noqa: E501
        if include_optional :
            return PlayerDetail(
                tag = '0', 
                name = '0', 
                exp_level = 56, 
                exp_points = 56, 
                trophies = 56, 
                highest_trophies = 56, 
                power_play_points = 56, 
                highestpower_play_points = 56, 
                solo_victories = 56, 
                duo_victories = 56, 
                best_robo_rumble_time = 56, 
                best_time_as_big_brawler = 56, 
                club = pybrawl.models.club_base.ClubBase(
                    tag = '0', 
                    name = '0', 
                    badge_id = 56, ), 
                brawlers = [
                    pybrawl.models.brawler.Brawler(
                        name = '0', 
                        id = 56, 
                        level = 56, 
                        count = 56, 
                        max_level = 56, 
                        icon_urls = pybrawl.models.brawler_icon_urls.Brawler_iconUrls(
                            medium = '0', ), )
                    ], 
                current_favouritebrawler = pybrawl.models.brawler.Brawler(
                    name = '0', 
                    id = 56, 
                    level = 56, 
                    count = 56, 
                    max_level = 56, 
                    icon_urls = pybrawl.models.brawler_icon_urls.Brawler_iconUrls(
                        medium = '0', ), ), 
                star_points = 56
            )
        else :
            return PlayerDetail(
        )

    def testPlayerDetail(self):
        """Test PlayerDetail"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
