# coding: utf-8

"""
    Brawl Stars API

    Unofficial Swagger definition for the official Brawl Stars API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pybrawl
from pybrawl.api.brawlers_api import BrawlersApi  # noqa: E501
from pybrawl.rest import ApiException


class TestBrawlersApi(unittest.TestCase):
    """BrawlersApi unit test stubs"""

    def setUp(self):
        self.api = pybrawl.api.brawlers_api.BrawlersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_getbrawlers(self):
        """Test case for getbrawlers

        Get list of available brawlers  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
