# coding: utf-8

"""
    Brawl Stars API

    Unofficial Swagger definition for the official Brawl Stars API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pybrawl
from pybrawl.models.battle_log_entry import BattleLogEntry  # noqa: E501
from pybrawl.rest import ApiException

class TestBattleLogEntry(unittest.TestCase):
    """BattleLogEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BattleLogEntry
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pybrawl.models.battle_log_entry.BattleLogEntry()  # noqa: E501
        if include_optional :
            return BattleLogEntry(
                type = '0', 
                battle_time = '0', 
                team = [
                    pybrawl.models.battle_log_team.BattleLogTeam(
                        tag = '0', 
                        name = '0', 
                        starting_trophies = 56, 
                        trophy_change = 56, 
                        crowns = 56, 
                        king_tower_hit_points = 56, 
                        princess_towers_hit_points = [
                            56
                            ], 
                        club = None, 
                        brawlers = [
                            pybrawl.models.brawler.Brawler(
                                name = '0', 
                                id = 56, 
                                level = 56, 
                                count = 56, 
                                max_level = 56, 
                                icon_urls = pybrawl.models.brawler_icon_urls.Brawler_iconUrls(
                                    medium = '0', ), )
                            ], )
                    ], 
                opponent = [
                    pybrawl.models.battle_log_team.BattleLogTeam(
                        tag = '0', 
                        name = '0', 
                        starting_trophies = 56, 
                        trophy_change = 56, 
                        crowns = 56, 
                        king_tower_hit_points = 56, 
                        princess_towers_hit_points = [
                            56
                            ], 
                        club = None, 
                        brawlers = [
                            pybrawl.models.brawler.Brawler(
                                name = '0', 
                                id = 56, 
                                level = 56, 
                                count = 56, 
                                max_level = 56, 
                                icon_urls = pybrawl.models.brawler_icon_urls.Brawler_iconUrls(
                                    medium = '0', ), )
                            ], )
                    ]
            )
        else :
            return BattleLogEntry(
        )

    def testBattleLogEntry(self):
        """Test BattleLogEntry"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
