# coding: utf-8

"""
    Brawl Stars API

    Unofficial Swagger definition for the official Brawl Stars API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from pybrawl.configuration import Configuration


class ClubMember(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'tag': 'str',
        'name': 'str',
        'exp_level': 'int',
        'trophies': 'int',
        'role': 'str',
        'last_seen': 'str',
        'club_rank': 'int',
        'previous_club_rank': 'int',
        'donations': 'int',
        'donations_received': 'int',
        'club_chest_points': 'int'
    }

    attribute_map = {
        'tag': 'tag',
        'name': 'name',
        'exp_level': 'expLevel',
        'trophies': 'trophies',
        'role': 'role',
        'last_seen': 'lastSeen',
        'club_rank': 'clubRank',
        'previous_club_rank': 'previousClubRank',
        'donations': 'donations',
        'donations_received': 'donationsReceived',
        'club_chest_points': 'clubChestPoints'
    }

    def __init__(self, tag=None, name=None, exp_level=None, trophies=None, role=None, last_seen=None, club_rank=None, previous_club_rank=None, donations=None, donations_received=None, club_chest_points=None, local_vars_configuration=None):  # noqa: E501
        """ClubMember - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._tag = None
        self._name = None
        self._exp_level = None
        self._trophies = None
        self._role = None
        self._last_seen = None
        self._club_rank = None
        self._previous_club_rank = None
        self._donations = None
        self._donations_received = None
        self._club_chest_points = None
        self.discriminator = None

        if tag is not None:
            self.tag = tag
        if name is not None:
            self.name = name
        if exp_level is not None:
            self.exp_level = exp_level
        if trophies is not None:
            self.trophies = trophies
        if role is not None:
            self.role = role
        if last_seen is not None:
            self.last_seen = last_seen
        if club_rank is not None:
            self.club_rank = club_rank
        if previous_club_rank is not None:
            self.previous_club_rank = previous_club_rank
        if donations is not None:
            self.donations = donations
        if donations_received is not None:
            self.donations_received = donations_received
        if club_chest_points is not None:
            self.club_chest_points = club_chest_points

    @property
    def tag(self):
        """Gets the tag of this ClubMember.  # noqa: E501


        :return: The tag of this ClubMember.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this ClubMember.


        :param tag: The tag of this ClubMember.  # noqa: E501
        :type: str
        """

        self._tag = tag

    @property
    def name(self):
        """Gets the name of this ClubMember.  # noqa: E501


        :return: The name of this ClubMember.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ClubMember.


        :param name: The name of this ClubMember.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def exp_level(self):
        """Gets the exp_level of this ClubMember.  # noqa: E501


        :return: The exp_level of this ClubMember.  # noqa: E501
        :rtype: int
        """
        return self._exp_level

    @exp_level.setter
    def exp_level(self, exp_level):
        """Sets the exp_level of this ClubMember.


        :param exp_level: The exp_level of this ClubMember.  # noqa: E501
        :type: int
        """

        self._exp_level = exp_level

    @property
    def trophies(self):
        """Gets the trophies of this ClubMember.  # noqa: E501


        :return: The trophies of this ClubMember.  # noqa: E501
        :rtype: int
        """
        return self._trophies

    @trophies.setter
    def trophies(self, trophies):
        """Sets the trophies of this ClubMember.


        :param trophies: The trophies of this ClubMember.  # noqa: E501
        :type: int
        """

        self._trophies = trophies

    @property
    def role(self):
        """Gets the role of this ClubMember.  # noqa: E501


        :return: The role of this ClubMember.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this ClubMember.


        :param role: The role of this ClubMember.  # noqa: E501
        :type: str
        """

        self._role = role

    @property
    def last_seen(self):
        """Gets the last_seen of this ClubMember.  # noqa: E501


        :return: The last_seen of this ClubMember.  # noqa: E501
        :rtype: str
        """
        return self._last_seen

    @last_seen.setter
    def last_seen(self, last_seen):
        """Sets the last_seen of this ClubMember.


        :param last_seen: The last_seen of this ClubMember.  # noqa: E501
        :type: str
        """

        self._last_seen = last_seen

    @property
    def club_rank(self):
        """Gets the club_rank of this ClubMember.  # noqa: E501


        :return: The club_rank of this ClubMember.  # noqa: E501
        :rtype: int
        """
        return self._club_rank

    @club_rank.setter
    def club_rank(self, club_rank):
        """Sets the club_rank of this ClubMember.


        :param club_rank: The club_rank of this ClubMember.  # noqa: E501
        :type: int
        """

        self._club_rank = club_rank

    @property
    def previous_club_rank(self):
        """Gets the previous_club_rank of this ClubMember.  # noqa: E501


        :return: The previous_club_rank of this ClubMember.  # noqa: E501
        :rtype: int
        """
        return self._previous_club_rank

    @previous_club_rank.setter
    def previous_club_rank(self, previous_club_rank):
        """Sets the previous_club_rank of this ClubMember.


        :param previous_club_rank: The previous_club_rank of this ClubMember.  # noqa: E501
        :type: int
        """

        self._previous_club_rank = previous_club_rank

    @property
    def donations(self):
        """Gets the donations of this ClubMember.  # noqa: E501


        :return: The donations of this ClubMember.  # noqa: E501
        :rtype: int
        """
        return self._donations

    @donations.setter
    def donations(self, donations):
        """Sets the donations of this ClubMember.


        :param donations: The donations of this ClubMember.  # noqa: E501
        :type: int
        """

        self._donations = donations

    @property
    def donations_received(self):
        """Gets the donations_received of this ClubMember.  # noqa: E501


        :return: The donations_received of this ClubMember.  # noqa: E501
        :rtype: int
        """
        return self._donations_received

    @donations_received.setter
    def donations_received(self, donations_received):
        """Sets the donations_received of this ClubMember.


        :param donations_received: The donations_received of this ClubMember.  # noqa: E501
        :type: int
        """

        self._donations_received = donations_received

    @property
    def club_chest_points(self):
        """Gets the club_chest_points of this ClubMember.  # noqa: E501


        :return: The club_chest_points of this ClubMember.  # noqa: E501
        :rtype: int
        """
        return self._club_chest_points

    @club_chest_points.setter
    def club_chest_points(self, club_chest_points):
        """Sets the club_chest_points of this ClubMember.


        :param club_chest_points: The club_chest_points of this ClubMember.  # noqa: E501
        :type: int
        """

        self._club_chest_points = club_chest_points

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClubMember):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ClubMember):
            return True

        return self.to_dict() != other.to_dict()
