# coding: utf-8

"""
    Brawl Stars API

    Unofficial Swagger definition for the official Brawl Stars API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://github.com/heyudude/brawlstars-swagger
"""


import pprint
import re  # noqa: F401

import six

from pybrawl.configuration import Configuration


class Club(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'tag': 'str',
        'name': 'str',
        'description': 'str',
        'trophies': 'int',
        'required_trophies': 'int',
        'member_list': 'list[ClubMember]'
    }

    attribute_map = {
        'tag': 'tag',
        'name': 'name',
        'description': 'description',
        'trophies': 'trophies',
        'required_trophies': 'requiredTrophies',
        'member_list': 'memberList'
    }

    def __init__(self, tag=None, name=None, description=None, trophies=None, required_trophies=None, member_list=None, local_vars_configuration=None):  # noqa: E501
        """Club - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._tag = None
        self._name = None
        self._description = None
        self._trophies = None
        self._required_trophies = None
        self._member_list = None
        self.discriminator = None

        if tag is not None:
            self.tag = tag
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if trophies is not None:
            self.trophies = trophies
        if required_trophies is not None:
            self.required_trophies = required_trophies
        if member_list is not None:
            self.member_list = member_list

    @property
    def tag(self):
        """Gets the tag of this Club.  # noqa: E501


        :return: The tag of this Club.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this Club.


        :param tag: The tag of this Club.  # noqa: E501
        :type tag: str
        """

        self._tag = tag

    @property
    def name(self):
        """Gets the name of this Club.  # noqa: E501


        :return: The name of this Club.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Club.


        :param name: The name of this Club.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this Club.  # noqa: E501


        :return: The description of this Club.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Club.


        :param description: The description of this Club.  # noqa: E501
        :type description: str
        """

        self._description = description

    @property
    def trophies(self):
        """Gets the trophies of this Club.  # noqa: E501


        :return: The trophies of this Club.  # noqa: E501
        :rtype: int
        """
        return self._trophies

    @trophies.setter
    def trophies(self, trophies):
        """Sets the trophies of this Club.


        :param trophies: The trophies of this Club.  # noqa: E501
        :type trophies: int
        """

        self._trophies = trophies

    @property
    def required_trophies(self):
        """Gets the required_trophies of this Club.  # noqa: E501


        :return: The required_trophies of this Club.  # noqa: E501
        :rtype: int
        """
        return self._required_trophies

    @required_trophies.setter
    def required_trophies(self, required_trophies):
        """Sets the required_trophies of this Club.


        :param required_trophies: The required_trophies of this Club.  # noqa: E501
        :type required_trophies: int
        """

        self._required_trophies = required_trophies

    @property
    def member_list(self):
        """Gets the member_list of this Club.  # noqa: E501


        :return: The member_list of this Club.  # noqa: E501
        :rtype: list[ClubMember]
        """
        return self._member_list

    @member_list.setter
    def member_list(self, member_list):
        """Sets the member_list of this Club.


        :param member_list: The member_list of this Club.  # noqa: E501
        :type member_list: list[ClubMember]
        """

        self._member_list = member_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Club):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Club):
            return True

        return self.to_dict() != other.to_dict()
