# coding: utf-8

"""
    Brawl Stars API

    Unofficial Swagger definition for the official Brawl Stars API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from pybrawl.configuration import Configuration


class PlayerDetail(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'tag': 'str',
        'name': 'str',
        'exp_level': 'int',
        'exp_points': 'int',
        'trophies': 'int',
        'highest_trophies': 'int',
        'power_play_points': 'int',
        'highestpower_play_points': 'int',
        'solo_victories': 'int',
        'duo_victories': 'int',
        'best_robo_rumble_time': 'int',
        'best_time_as_big_brawler': 'int',
        'club': 'ClubBase',
        'brawlers': 'list[Brawler]',
        'current_favouritebrawler': 'Brawler',
        'star_points': 'int'
    }

    attribute_map = {
        'tag': 'tag',
        'name': 'name',
        'exp_level': 'expLevel',
        'exp_points': 'expPoints',
        'trophies': 'trophies',
        'highest_trophies': 'highestTrophies',
        'power_play_points': 'powerPlayPoints',
        'highestpower_play_points': 'highestpowerPlayPoints',
        'solo_victories': 'soloVictories',
        'duo_victories': 'duoVictories',
        'best_robo_rumble_time': 'BestRoboRumbleTime',
        'best_time_as_big_brawler': 'BestTimeAsBigBrawler',
        'club': 'club',
        'brawlers': 'Brawlers',
        'current_favouritebrawler': 'currentFavouritebrawler',
        'star_points': 'starPoints'
    }

    def __init__(self, tag=None, name=None, exp_level=None, exp_points=None, trophies=None, highest_trophies=None, power_play_points=None, highestpower_play_points=None, solo_victories=None, duo_victories=None, best_robo_rumble_time=None, best_time_as_big_brawler=None, club=None, brawlers=None, current_favouritebrawler=None, star_points=None, local_vars_configuration=None):  # noqa: E501
        """PlayerDetail - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._tag = None
        self._name = None
        self._exp_level = None
        self._exp_points = None
        self._trophies = None
        self._highest_trophies = None
        self._power_play_points = None
        self._highestpower_play_points = None
        self._solo_victories = None
        self._duo_victories = None
        self._best_robo_rumble_time = None
        self._best_time_as_big_brawler = None
        self._club = None
        self._brawlers = None
        self._current_favouritebrawler = None
        self._star_points = None
        self.discriminator = None

        if tag is not None:
            self.tag = tag
        if name is not None:
            self.name = name
        if exp_level is not None:
            self.exp_level = exp_level
        if exp_points is not None:
            self.exp_points = exp_points
        if trophies is not None:
            self.trophies = trophies
        if highest_trophies is not None:
            self.highest_trophies = highest_trophies
        if power_play_points is not None:
            self.power_play_points = power_play_points
        if highestpower_play_points is not None:
            self.highestpower_play_points = highestpower_play_points
        if solo_victories is not None:
            self.solo_victories = solo_victories
        if duo_victories is not None:
            self.duo_victories = duo_victories
        if best_robo_rumble_time is not None:
            self.best_robo_rumble_time = best_robo_rumble_time
        if best_time_as_big_brawler is not None:
            self.best_time_as_big_brawler = best_time_as_big_brawler
        if club is not None:
            self.club = club
        if brawlers is not None:
            self.brawlers = brawlers
        if current_favouritebrawler is not None:
            self.current_favouritebrawler = current_favouritebrawler
        if star_points is not None:
            self.star_points = star_points

    @property
    def tag(self):
        """Gets the tag of this PlayerDetail.  # noqa: E501


        :return: The tag of this PlayerDetail.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this PlayerDetail.


        :param tag: The tag of this PlayerDetail.  # noqa: E501
        :type: str
        """

        self._tag = tag

    @property
    def name(self):
        """Gets the name of this PlayerDetail.  # noqa: E501


        :return: The name of this PlayerDetail.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PlayerDetail.


        :param name: The name of this PlayerDetail.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def exp_level(self):
        """Gets the exp_level of this PlayerDetail.  # noqa: E501


        :return: The exp_level of this PlayerDetail.  # noqa: E501
        :rtype: int
        """
        return self._exp_level

    @exp_level.setter
    def exp_level(self, exp_level):
        """Sets the exp_level of this PlayerDetail.


        :param exp_level: The exp_level of this PlayerDetail.  # noqa: E501
        :type: int
        """

        self._exp_level = exp_level

    @property
    def exp_points(self):
        """Gets the exp_points of this PlayerDetail.  # noqa: E501


        :return: The exp_points of this PlayerDetail.  # noqa: E501
        :rtype: int
        """
        return self._exp_points

    @exp_points.setter
    def exp_points(self, exp_points):
        """Sets the exp_points of this PlayerDetail.


        :param exp_points: The exp_points of this PlayerDetail.  # noqa: E501
        :type: int
        """

        self._exp_points = exp_points

    @property
    def trophies(self):
        """Gets the trophies of this PlayerDetail.  # noqa: E501


        :return: The trophies of this PlayerDetail.  # noqa: E501
        :rtype: int
        """
        return self._trophies

    @trophies.setter
    def trophies(self, trophies):
        """Sets the trophies of this PlayerDetail.


        :param trophies: The trophies of this PlayerDetail.  # noqa: E501
        :type: int
        """

        self._trophies = trophies

    @property
    def highest_trophies(self):
        """Gets the highest_trophies of this PlayerDetail.  # noqa: E501


        :return: The highest_trophies of this PlayerDetail.  # noqa: E501
        :rtype: int
        """
        return self._highest_trophies

    @highest_trophies.setter
    def highest_trophies(self, highest_trophies):
        """Sets the highest_trophies of this PlayerDetail.


        :param highest_trophies: The highest_trophies of this PlayerDetail.  # noqa: E501
        :type: int
        """

        self._highest_trophies = highest_trophies

    @property
    def power_play_points(self):
        """Gets the power_play_points of this PlayerDetail.  # noqa: E501


        :return: The power_play_points of this PlayerDetail.  # noqa: E501
        :rtype: int
        """
        return self._power_play_points

    @power_play_points.setter
    def power_play_points(self, power_play_points):
        """Sets the power_play_points of this PlayerDetail.


        :param power_play_points: The power_play_points of this PlayerDetail.  # noqa: E501
        :type: int
        """

        self._power_play_points = power_play_points

    @property
    def highestpower_play_points(self):
        """Gets the highestpower_play_points of this PlayerDetail.  # noqa: E501


        :return: The highestpower_play_points of this PlayerDetail.  # noqa: E501
        :rtype: int
        """
        return self._highestpower_play_points

    @highestpower_play_points.setter
    def highestpower_play_points(self, highestpower_play_points):
        """Sets the highestpower_play_points of this PlayerDetail.


        :param highestpower_play_points: The highestpower_play_points of this PlayerDetail.  # noqa: E501
        :type: int
        """

        self._highestpower_play_points = highestpower_play_points

    @property
    def solo_victories(self):
        """Gets the solo_victories of this PlayerDetail.  # noqa: E501


        :return: The solo_victories of this PlayerDetail.  # noqa: E501
        :rtype: int
        """
        return self._solo_victories

    @solo_victories.setter
    def solo_victories(self, solo_victories):
        """Sets the solo_victories of this PlayerDetail.


        :param solo_victories: The solo_victories of this PlayerDetail.  # noqa: E501
        :type: int
        """

        self._solo_victories = solo_victories

    @property
    def duo_victories(self):
        """Gets the duo_victories of this PlayerDetail.  # noqa: E501


        :return: The duo_victories of this PlayerDetail.  # noqa: E501
        :rtype: int
        """
        return self._duo_victories

    @duo_victories.setter
    def duo_victories(self, duo_victories):
        """Sets the duo_victories of this PlayerDetail.


        :param duo_victories: The duo_victories of this PlayerDetail.  # noqa: E501
        :type: int
        """

        self._duo_victories = duo_victories

    @property
    def best_robo_rumble_time(self):
        """Gets the best_robo_rumble_time of this PlayerDetail.  # noqa: E501


        :return: The best_robo_rumble_time of this PlayerDetail.  # noqa: E501
        :rtype: int
        """
        return self._best_robo_rumble_time

    @best_robo_rumble_time.setter
    def best_robo_rumble_time(self, best_robo_rumble_time):
        """Sets the best_robo_rumble_time of this PlayerDetail.


        :param best_robo_rumble_time: The best_robo_rumble_time of this PlayerDetail.  # noqa: E501
        :type: int
        """

        self._best_robo_rumble_time = best_robo_rumble_time

    @property
    def best_time_as_big_brawler(self):
        """Gets the best_time_as_big_brawler of this PlayerDetail.  # noqa: E501


        :return: The best_time_as_big_brawler of this PlayerDetail.  # noqa: E501
        :rtype: int
        """
        return self._best_time_as_big_brawler

    @best_time_as_big_brawler.setter
    def best_time_as_big_brawler(self, best_time_as_big_brawler):
        """Sets the best_time_as_big_brawler of this PlayerDetail.


        :param best_time_as_big_brawler: The best_time_as_big_brawler of this PlayerDetail.  # noqa: E501
        :type: int
        """

        self._best_time_as_big_brawler = best_time_as_big_brawler

    @property
    def club(self):
        """Gets the club of this PlayerDetail.  # noqa: E501


        :return: The club of this PlayerDetail.  # noqa: E501
        :rtype: ClubBase
        """
        return self._club

    @club.setter
    def club(self, club):
        """Sets the club of this PlayerDetail.


        :param club: The club of this PlayerDetail.  # noqa: E501
        :type: ClubBase
        """

        self._club = club

    @property
    def brawlers(self):
        """Gets the brawlers of this PlayerDetail.  # noqa: E501


        :return: The brawlers of this PlayerDetail.  # noqa: E501
        :rtype: list[Brawler]
        """
        return self._brawlers

    @brawlers.setter
    def brawlers(self, brawlers):
        """Sets the brawlers of this PlayerDetail.


        :param brawlers: The brawlers of this PlayerDetail.  # noqa: E501
        :type: list[Brawler]
        """

        self._brawlers = brawlers

    @property
    def current_favouritebrawler(self):
        """Gets the current_favouritebrawler of this PlayerDetail.  # noqa: E501


        :return: The current_favouritebrawler of this PlayerDetail.  # noqa: E501
        :rtype: Brawler
        """
        return self._current_favouritebrawler

    @current_favouritebrawler.setter
    def current_favouritebrawler(self, current_favouritebrawler):
        """Sets the current_favouritebrawler of this PlayerDetail.


        :param current_favouritebrawler: The current_favouritebrawler of this PlayerDetail.  # noqa: E501
        :type: Brawler
        """

        self._current_favouritebrawler = current_favouritebrawler

    @property
    def star_points(self):
        """Gets the star_points of this PlayerDetail.  # noqa: E501


        :return: The star_points of this PlayerDetail.  # noqa: E501
        :rtype: int
        """
        return self._star_points

    @star_points.setter
    def star_points(self, star_points):
        """Sets the star_points of this PlayerDetail.


        :param star_points: The star_points of this PlayerDetail.  # noqa: E501
        :type: int
        """

        self._star_points = star_points

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlayerDetail):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PlayerDetail):
            return True

        return self.to_dict() != other.to_dict()
